# https://cloud.google.com/solutions/managing-infrastructure-as-code

steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/${PROJECT_ID}/${_WEB_SERVICE}", "${_WEB_SERVICE}"]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_WEB_SERVICE}"]

  - id: "tf init"
    name: "hashicorp/terraform:${_TERRAFORM_VERSION}"
    args: ["init"]

  - id: "tf plan"
    name: "hashicorp/terraform:${_TERRAFORM_VERSION}"
    args: ["plan"]

  - id: "tf apply"
    name: "hashicorp/terraform:${_TERRAFORM_VERSION}"
    args: ["apply -auto-approve -var project=${PROJECT_ID}"]

substitutions:
  _WEB_SERVICE: web-service
  _TERRAFORM_VERSION: "0.14.4"
